name: flutter_meetup_hh_website
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12
  path_provider: ^1.6.27
  url_strategy: ^0.1.1
  flutter_markdown: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/jsons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons/MaterialIcons-Regular.ttf